language: php
php:
  - 5.6
env:
  - MAGE=1.9.0.1
before_script:
  - MAGE_DIR=tests/magento
  # Copying travis composer.json to test only module
  - cp -f .travis/composer.json composer.json
  # Installing dependencies
  - composer install
  # Installing magento version with prepared DB dump
  - bin/mage-ci install $MAGE_DIR $MAGE magento -c -r http://mage-ci.ecomdev.org
  # Installing EcomDev_PHPUnit module
  - bin/mage-ci install-module $MAGE_DIR $(pwd)
  # Configuring EcomDev_PHPUnit module
  - bin/mage-ci shell $MAGE_DIR ecomdev-phpunit.php -a magento-config --db-name magento --same-db 1 --base-url http://test.magento.com/
  # Configuring test suite
  - bin/mage-ci shell $MAGE_DIR ecomdev-phpunit.php -a change-status --enable
  # Copying phpunit.xml for travis builds
  - cp .travis/phpunit.xml $MAGE_DIR/phpunit.xml
script:
  # output php ini info for checking the problem
  - bin/mage-ci phpunit $MAGE_DIR --colors --coverage-text -d display_errors=1
